name: SlimefunAccelerator
author: balugaq
description: This is a Slimefun addon.
main: com.balugaq.slimefunaccelerator.implementation.SlimefunAccelerator
website: https://github.com/balugaq/SlimefunAccelerator
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
commands:
  slimefunaccelerator:
    aliases:
      - sa
      - accelerator
    description: /slimefunaccelerator
    usage: /slimefunaccelerator <sub>
